exclude: |
  (?x)^(
    build/|
    install/|
    log/|
    \.venv/|
    ros_ws/src/omniseer_gz_assets/|
    firmware/|
    hardware/|
    docs/|
    notes/|
    sim/models/|
    ros_ws/src/.*/models/|
    ros_ws/src/.*/meshes/|
    .*\.dae$| .*\.obj$| .*\.mtl$| .*\.sdf$| .*\.world$| .*\.pgm$
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        files: ^(include/|src/|ros_ws/src/(analysis|bringup|omniseer_description|omniseer_test|yolo_ros)/).*\.(c|cc|cpp|cxx|h|hh|hpp|hxx|cu|cuh)$
        exclude: ^(third_party/|external/|vendor/|ros_ws/src/.*/(models|meshes|gazebo|deps|third_party|external)/|build/|install/|log/)
