site_name: omniseer
repo_url: https://github.com/jburo1/omniseer
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
  features:
    - navigation.sections
    - navigation.instant
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
plugins:
  - search
  - git-revision-date-localized
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Software:
    - Build pipeline: software/build_pipeline.md
    - ROS packages: software/ros_packages.md
  - Hardware:
    - Circuit: hardware/circuit.md
    - Wiring guide: hardware/wiring.md
