[pytest]
addopts = --import-mode=importlib
norecursedirs =
    .git
    .venv
    build
    install
    log
    ros_ws/build
    ros_ws/install
    ros_ws/log
    uros_ws/build
    uros_ws/install
    uros_ws/log
    vision/build
    vision/build-*
    firmware/.pio
