# bt_navigator:
#   ros__parameters:
#     default_bt_xml_filename: nav2_bt_navigator/navigate_w_replanning_and_recovery.xml
#     goal_checkers:
#       plugin_ids: ["general_goal_checker"]
#       plugin_types: ["nav2_controller::SimpleGoalChecker"]
#     general_goal_checker:
#       xyz_goal_tolerance: 0.10
#       yaw_goal_tolerance: 0.10
#       stateful: true

planner_server:
  ros__parameters:
    planner_plugins: ["Grid"]
    Grid:
      plugin: nav2_smac_planner/SmacPlanner2D
      tolerance: 0.25
      downsample_costmap: true
      motion_model_for_search: MOORE     # 8-dir for holonomic
      cache_obstacle_heuristic: true

smoother_server:
  ros__parameters:
    smoother_plugins: ["Simple"]
    Simple:
      plugin: nav2_smoother::SimpleSmoother
      tolerance: 0.1
      max_its: 100
      w_curve: 30.0
      w_dist: 0.0

controller_server:
  ros__parameters:
    use_stamped_cmd_vel: true            
    controller_plugins: ["DWB"]
    DWB:
      plugin: dwb_core::DWBLocalPlanner
      min_vel_x: -0.6
      max_vel_x:  0.6
      min_vel_y: -0.6
      max_vel_y:  0.6
      min_vel_theta: -2.5
      max_vel_theta:  2.5
      acc_lim_x: 1.0
      acc_lim_y: 1.0
      acc_lim_theta: 3.0
      vx_samples: 10
      vy_samples: 10
      vtheta_samples: 20
      sim_time: 2.0
      linear_granularity: 0.05
      angular_granularity: 0.025
      critics: ["ObstacleFootprint","Twirling","GoalAlign","PathAlign","PathDist","GoalDist","RotateToGoal"]

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint

global_costmap:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    use_sim_time: false
    update_frequency: 2.0
    publish_frequency: 1.0
    resolution: 0.05
    footprint: [[0.20,0.17],[0.20,-0.17],[-0.20,-0.17],[-0.20,0.17]]   # update with your true extents
    plugins: ["static_layer","obstacle_layer","inflation_layer"]
    static_layer:
      map_subscribe_transient_local: true
    obstacle_layer:
      observation_sources: lidar
      lidar:
        topic: scan
        data_type: LaserScan
        expected_update_rate: 0.0
        clearing: true
        marking: true
        obstacle_range: 3.5
        raytrace_range: 5.0
    inflation_layer:
      inflation_radius: 0.45
      cost_scaling_factor: 3.0

local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    use_sim_time: false
    update_frequency: 10.0
    publish_frequency: 5.0
    rolling_window: true
    width: 4.0
    height: 4.0
    resolution: 0.05
    footprint: [[0.20,0.17],[0.20,-0.17],[-0.20,-0.17],[-0.20,0.17]]
    plugins: ["obstacle_layer","inflation_layer"]
    obstacle_layer:
      observation_sources: lidar
      lidar:
        topic: scan
        data_type: LaserScan
        expected_update_rate: 0.0
        clearing: true
        marking: true
        obstacle_range: 3.5
        raytrace_range: 5.0
    inflation_layer:
      inflation_radius: 0.45
      cost_scaling_factor: 3.0

waypoint_follower:
  ros__parameters:
    loop_rate: 20

# lifecycle manager to keep Nav2 nodes alive
lifecycle_manager:
  ros__parameters:
    autostart: true
    bond_timeout: 0.0
    node_names: ["controller_server","planner_server","behavior_server","bt_navigator","smoother_server","waypoint_follower"]
