# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from robot_diag_control.api import robot_gateway_pb2 as robot__diag__control_dot_api_dot_robot__gateway__pb2


class RobotGatewayStub(object):
    """Minimal operator-facing control/status contract for the first gateway slices.

    Versioning rule:
    - evolve additively
    - do not repurpose field numbers
    - keep ROS resource names out of this contract
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSystemStatus = channel.unary_unary(
                '/omniseer.gateway.v1.RobotGateway/GetSystemStatus',
                request_serializer=robot__diag__control_dot_api_dot_robot__gateway__pb2.GetSystemStatusRequest.SerializeToString,
                response_deserializer=robot__diag__control_dot_api_dot_robot__gateway__pb2.SystemStatus.FromString,
                )
        self.SetPreviewMode = channel.unary_unary(
                '/omniseer.gateway.v1.RobotGateway/SetPreviewMode',
                request_serializer=robot__diag__control_dot_api_dot_robot__gateway__pb2.SetPreviewModeRequest.SerializeToString,
                response_deserializer=robot__diag__control_dot_api_dot_robot__gateway__pb2.SetPreviewModeResponse.FromString,
                )


class RobotGatewayServicer(object):
    """Minimal operator-facing control/status contract for the first gateway slices.

    Versioning rule:
    - evolve additively
    - do not repurpose field numbers
    - keep ROS resource names out of this contract
    """

    def GetSystemStatus(self, request, context):
        """Returns the latest normalized gateway status snapshot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPreviewMode(self, request, context):
        """Enables or disables preview mode.
        When enabled=false, the profile field is ignored.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=robot__diag__control_dot_api_dot_robot__gateway__pb2.GetSystemStatusRequest.FromString,
                    response_serializer=robot__diag__control_dot_api_dot_robot__gateway__pb2.SystemStatus.SerializeToString,
            ),
            'SetPreviewMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPreviewMode,
                    request_deserializer=robot__diag__control_dot_api_dot_robot__gateway__pb2.SetPreviewModeRequest.FromString,
                    response_serializer=robot__diag__control_dot_api_dot_robot__gateway__pb2.SetPreviewModeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omniseer.gateway.v1.RobotGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RobotGateway(object):
    """Minimal operator-facing control/status contract for the first gateway slices.

    Versioning rule:
    - evolve additively
    - do not repurpose field numbers
    - keep ROS resource names out of this contract
    """

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omniseer.gateway.v1.RobotGateway/GetSystemStatus',
            robot__diag__control_dot_api_dot_robot__gateway__pb2.GetSystemStatusRequest.SerializeToString,
            robot__diag__control_dot_api_dot_robot__gateway__pb2.SystemStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetPreviewMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omniseer.gateway.v1.RobotGateway/SetPreviewMode',
            robot__diag__control_dot_api_dot_robot__gateway__pb2.SetPreviewModeRequest.SerializeToString,
            robot__diag__control_dot_api_dot_robot__gateway__pb2.SetPreviewModeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
