#!/usr/bin/env python3
"""Export the authoritative Omniseer hardware BOM workbook to public docs."""

from __future__ import annotations

import xml.etree.ElementTree as ET
from decimal import Decimal, InvalidOperation
from pathlib import Path
from shutil import copy2
from zipfile import ZipFile

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SOURCE_BOM = REPOSITORY_ROOT / "hardware/bom/omniseer_bom.ods"
OUTPUT_PAGE = REPOSITORY_ROOT / "docs/hardware/bill-of-materials.md"
PUBLIC_BOM = OUTPUT_PAGE.parent / SOURCE_BOM.name

NS = {
    "office": "urn:oasis:names:tc:opendocument:xmlns:office:1.0",
    "table": "urn:oasis:names:tc:opendocument:xmlns:table:1.0",
}


def attribute(namespace: str, name: str) -> str:
    return f"{{{NS[namespace]}}}{name}"


def read_sheet(path: Path, sheet_name: str) -> list[list[tuple[str, str | None]]]:
    """Read displayed text and cached numeric values from an ODS sheet."""
    with ZipFile(path) as archive:
        root = ET.fromstring(archive.read("content.xml"))

    for sheet in root.findall(".//table:table", NS):
        if sheet.get(attribute("table", "name")) != sheet_name:
            continue

        rows = []
        for row in sheet.findall("table:table-row", NS):
            cells = []
            for cell in row.findall("table:table-cell", NS):
                repeat = int(cell.get(attribute("table", "number-columns-repeated"), "1"))
                displayed = "".join(cell.itertext()).strip()
                value = cell.get(attribute("office", "value"))
                cells.extend([(displayed, value)] * repeat)
            rows.append(cells)
        return rows
    raise ValueError(f"sheet {sheet_name!r} was not found in {path}")


def decimal_value(value: str | None) -> Decimal | None:
    if value in (None, ""):
        return None
    try:
        return Decimal(value)
    except InvalidOperation as exc:
        raise ValueError(f"invalid numeric value in BOM: {value!r}") from exc


def format_cad(value: str | None) -> str:
    amount = decimal_value(value)
    return "TBD" if amount is None else f"CAD ${amount:,.2f}"


def markdown_cell(value: str) -> str:
    return " ".join(value.replace("|", "\\|").split()) or "—"


def export_markdown(rows: list[list[tuple[str, str | None]]]) -> str:
    header_index = next(
        index
        for index, row in enumerate(rows)
        if [cell[0] for cell in row[:8]]
        == [
            "Category",
            "Item",
            "Qty",
            "Unit Price (CAD)",
            "Extended (CAD)",
            "Specifications / Value",
            "Description",
            "Cost Status",
        ]
    )
    entries = []
    total = None
    for row in rows[header_index + 1 :]:
        values = row + [("", None)] * max(0, 8 - len(row))
        if values[0][0] == "Known priced total (CAD)":
            total = values[1][1]
            break
        if values[0][0]:
            entries.append(values)

    if total is None:
        raise ValueError("BOM is missing the known priced total")

    lines = [
        "# Bill of Materials",
        "",
        "Costs are approximate CAD purchase costs. The downloadable spreadsheet is the "
        "authoritative BOM; this page is generated from it.",
        "",
        "| Category | Item | Qty | Unit price | Extended cost | Status |",
        "| --- | --- | ---: | ---: | ---: | --- |",
    ]
    for entry in entries:
        category, item, quantity, unit_price, extended_cost, _, _, status = entry[:8]
        lines.append(
            "| "
            + " | ".join(
                (
                    markdown_cell(category[0]),
                    markdown_cell(item[0]),
                    markdown_cell(quantity[0]),
                    format_cad(unit_price[1]),
                    format_cad(extended_cost[1]),
                    markdown_cell(status[0] or ("Priced" if unit_price[1] else "TBD")),
                )
            )
            + " |"
        )
    lines.extend(
        (
            "",
            f"## Total known hardware cost: {format_cad(total)}",
            "",
            f"[Download the authoritative BOM spreadsheet]({SOURCE_BOM.name})",
            "",
            "<!-- Generated by scripts/export_bom.py; do not edit this file manually. -->",
            "",
        )
    )
    return "\n".join(lines)


def main() -> None:
    rows = read_sheet(SOURCE_BOM, "BOM")
    OUTPUT_PAGE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PAGE.write_text(export_markdown(rows), encoding="utf-8")
    copy2(SOURCE_BOM, PUBLIC_BOM)
    print(f"Exported {SOURCE_BOM.relative_to(REPOSITORY_ROOT)} to {OUTPUT_PAGE.relative_to(REPOSITORY_ROOT)}")


if __name__ == "__main__":
    main()
