name: docs

on:
  push:
    branches: [master]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "scripts/docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build docs
        shell: bash
        run: |
          set -eux
          python3 -m pip install --upgrade pip
          python3 -m pip install \
            mkdocs-material \
            mkdocs-git-revision-date-localized-plugin
          mkdocs build --strict

      - name: Configure git
        shell: bash
        run: |
          set -eux
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Deploy docs
        shell: bash
        run: |
          set -eux
          mkdocs gh-deploy --clean --force --verbose
